### ISSUE TITLE
PyPI release

### ISSUE THREAD

**Issue by adamchainz** [AngellusMortis/django_microsoft_auth#416]
#405 fixed installation with the latest pip, by not using pip internals. Please can you release it on PyPI, as currently `pip install django-microsoft-auth` fails with:

```
      Complete output (7 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/private/var/folders/kq/02p9h16n7zv_z7bhzmg6y_pm0000gn/T/pip-resolver-g8cwvonq/django-microsoft-auth/setup.py", line 39, in <module>
          requirements[req] = [str(req.req) for req in reqs]
        File "/private/var/folders/kq/02p9h16n7zv_z7bhzmg6y_pm0000gn/T/pip-resolver-g8cwvonq/django-microsoft-auth/setup.py", line 39, in <listcomp>
          requirements[req] = [str(req.req) for req in reqs]
      AttributeError: 'ParsedRequirement' object has no attribute 'req'
      ----------------------------------------
```

**Comment by RyanJohannesBland** [comment]
Can you explain what you mean by "Not using pip internals"? I'm currently receiving the same error.

**Comment by adamchainz** [comment]
https://github.com/AngellusMortis/django_microsoft_auth/pull/405/files#diff-2eeaed663bd0d25b7e608891384b7298L12

**Comment by spochic** [comment]
What needs to be done to release the fix on PyPI? Thanks

**Comment by chenbr** [comment]
@AngellusMortis  can we get these released to pypi?

**Comment by CVirus** [comment]
Any hope?

**Comment by AngellusMortis** [comment]
New release out.
